services:
  backend:
    container_name: mydigitalhub-backend
    build: ./backend
    restart: unless-stopped
    env_file: 
      - ./backend/.env
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: strapiDB
      DATABASE_PORT: 3306
      DATABASE_NAME: myDigitalHub
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./backend/config:/opt/app/config
      - ./backend/src:/opt/app/src
      - ./backend/package.json:/opt/package.json
      - ./backend/yarn.lock:/opt/yarn.lock
      - ./backend/.env:/opt/app/.env
      - ./backend/public/uploads:/opt/app/public/uploads
    ports:
      - 1337:1337
    # networks:
    #   - mydigitalhub-backend
    #   - mydigitalhub-frontend
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: ./backend/.env
    image: mariadb:latest
    environment:
      MYSQL_USER: strapi
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_PASSWORD: strapi
      MYSQL_DATABASE: myDigitalHub
    ports:
      - 3306:3306
    volumes:
      - strapi-data:/var/lib/mysql
      #- ./data:/var/lib/mysql # if you want to use a bind folder
    # networks:
    #   - mydigitalhub-backend

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    # networks:
    #   - mydigitalhub-backend

  frontend:
    build: ./frontend
    # environment:
    #   NEXT_PUBLIC_STRAPI_URL: http://localhost:1337
    #   NEXTAUTH_SECRET: secret
    #   NEXTAUTH_URL: http://localhost:3000
    ports:
      - 3000:3000
    container_name: myDigitalHub-frontend
    stdin_open: true
    depends_on:
      - backend
    restart: unless-stopped
    # networks:
    #   - mydigitalhub-backend
    #   - public-network

volumes:
  strapi-data:
# networks:
#   mydigitalhub-backend:
#   mydigitalhub-frontend: